// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVsqbyQt7F2eaPAFHbM4d80JTfZJnVFP4',
    appId: '1:825033090624:web:f6e8b382c9bf74760e61a5',
    messagingSenderId: '825033090624',
    projectId: 'miyuki-b1c80',
    authDomain: 'miyuki-b1c80.firebaseapp.com',
    databaseURL: 'https://miyuki-b1c80-default-rtdb.firebaseio.com',
    storageBucket: 'miyuki-b1c80.appspot.com',
    measurementId: 'G-70HQFNVTSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcDle3v-4nfMDR-pRtrueKhL5KE5xY1pI',
    appId: '1:825033090624:android:1dd211ce1582f4bc0e61a5',
    messagingSenderId: '825033090624',
    projectId: 'miyuki-b1c80',
    databaseURL: 'https://miyuki-b1c80-default-rtdb.firebaseio.com',
    storageBucket: 'miyuki-b1c80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANhUDU63XzM5BVrRCmDgfUC9yrGWutzOc',
    appId: '1:825033090624:ios:2c292960e64285ca0e61a5',
    messagingSenderId: '825033090624',
    projectId: 'miyuki-b1c80',
    databaseURL: 'https://miyuki-b1c80-default-rtdb.firebaseio.com',
    storageBucket: 'miyuki-b1c80.appspot.com',
    androidClientId: '825033090624-6lc4omgng92r3oqrpfuphchrsndrah6l.apps.googleusercontent.com',
    iosClientId: '825033090624-o2bit2lb3bflome1s2839qfsbvs3mvgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.project5Miyuki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANhUDU63XzM5BVrRCmDgfUC9yrGWutzOc',
    appId: '1:825033090624:ios:2c292960e64285ca0e61a5',
    messagingSenderId: '825033090624',
    projectId: 'miyuki-b1c80',
    databaseURL: 'https://miyuki-b1c80-default-rtdb.firebaseio.com',
    storageBucket: 'miyuki-b1c80.appspot.com',
    androidClientId: '825033090624-6lc4omgng92r3oqrpfuphchrsndrah6l.apps.googleusercontent.com',
    iosClientId: '825033090624-o2bit2lb3bflome1s2839qfsbvs3mvgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.project5Miyuki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVsqbyQt7F2eaPAFHbM4d80JTfZJnVFP4',
    appId: '1:825033090624:web:19ae9f05869524740e61a5',
    messagingSenderId: '825033090624',
    projectId: 'miyuki-b1c80',
    authDomain: 'miyuki-b1c80.firebaseapp.com',
    databaseURL: 'https://miyuki-b1c80-default-rtdb.firebaseio.com',
    storageBucket: 'miyuki-b1c80.appspot.com',
    measurementId: 'G-EPF2XVGQQC',
  );

}